name       : ted
version    : 2.23
release    : 1
source     :
    - http://ftp.nluug.nl/pub/editors/ted/ted-2.23.src.tar.gz : 3fa992c2bc96af3ca788ef941cb5314f4a1d843202efd0201b8b4ee9adbf316c
license    : GPL-2.0
component  : editor
summary    : An easy rich text processor
description: |
    Ted is an an easy to use rich text processor. It can save in Microsoft Word-compatible rich text format and has suppport for headers, footers, tables, different fonts, text alignment, and other features common in word processors. Ted contains spell checking and is a very light-weight and fast word processor, making it ideal for older computers and embedded systems.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(ice)
    - pkgconfig(libpcre)
    - pkgconfig(libtiff-4)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - pkgconfig(xft)
    - pkgconfig(xpm)
    - libjpeg-turbo-devel
    - libpaper-devel
    - libpng12
    - lsb-release
build      : |
    %make -j1
install    : |
    mkdir %installroot%
    %make_install -j1
